services:
  goserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      APP_ENV: ${APP_ENV}
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - ./.env:/app/.env
      - ./db:/app/db
      - ./internal/config/config.yml:/app/internal/config/config.yml

networks:
  default:
    driver: bridge
    ipam:
      driver: default
