services:
  goserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: goserver
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      APP_ENV: ${APP_ENV}
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - ./.env:/app/.env
      - ./db:/app/db
      - ./internal/config/config.yml:/app/internal/config/config.yml
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: ${DOCKER_SHARED_NET}
