server:
  port: 80
  addr:
    - "http://localhost:8080"

web:
  open: true
  title: "那人的庭院"
  desc: "人生如逆旅，我亦是行人。"
  nav_list:
    -
      title: "首页"
      path: "#"
    -
      title: "关于"
      path: "#about"
    -
      title: "Memos"
      path: "http://yvenchang.cn:4200"
    -
      title: "Trending"
      path: "https://yvenchang.cn/today.html"

database:
  host: "localhost"
  user: "root"
  password: "123456"
  name: "demo"

auth:
  id: 1
  user: "admin"
  password: "123456"
  sign_key: "123456"
  local_path: "./db/auth"
  issuer: "yven_server"

log:
  level: "info"
